FROM ubuntu:20.04

# Отключим попытку взаимодействия с пользователем
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    g++ make cmake git \
    librabbitmq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY producer_rmq.cpp .

RUN g++ producer_rmq.cpp -o producer_rmq -lrabbitmq -std=c++11

CMD ["./producer_rmq", "-n", "10", "-m", "10"]
